### ISSUE TITLE
Typescript version

### ISSUE THREAD

**Issue by amirhouieh** [the-road-to-react-with-firebase/react-mobx-firebase-authentication#1]
I have made a typescript version. [Here is the link to my fork](https://github.com/amirhouieh/react-mobx-firebase-authentication-typescript). Thought you might want to add it to the README .

**Comment by rwieruch** [comment]
Hey! Do you want to create the PR for it? Just add a new header with something like 

# Variations

* [typescript-react-mobx-firebase-authentication](link)
